1. What is the difference between ConfigMap and Secrets?
A: At the high level both Secrets and ConfigMaps are used to store the configuration data. 
The difference between the Secrets and ConfigMaps are:
- Secrets are used to store the sensitive data like passwords, tokens, ssh keys etc.
- ConfigMaps are used to store the non-sensitive data like application configuration, properties files etc. nginx configuration files, application.properties files etc.mysql.properties files etc.

2. What are the different types of Secrets?
A: There are 4 types of Secrets in Kubernetes:
- Opaque/Generic: Used to store the passwords, ssh keys, tokens etc.
- Docker-Registry: Used to store the docker registry credentials. To pull the images from the private registry. We can use this with the imagePullSecrets in the POD spec.
- TLS: Used to store the TLS/SSL certificates. Used by Ingress resource to terminate the SSL traffic.
- Service Account Token: Used to access the API server from the POD.

3. We have noticed admins/users are updating secrets which are causing issues. How can we prevent this?
A: Immutable Secrets is used to prevent the users from updating the secrets. Once the secret is created, it cannot be updated. If you want to update the secret, you need to delete the existing secret and create a new secret.
immutable: true

The challange is secret cannot be updated but it can be deleted and recreated. This can be achived by using External Secrets using the External Secrets Operator(ESO).

4. What is a External Secrets Operator(ESO)?
A: External Secrets Operator is used to manage the secrets in the external secret management systems like AWS Secrets Manager, Azure Key Vault, HashiCorp Vault etc.
We can deploy ESO with Helm Chart. Using ESO password, tokens, ssh keys etc can be stored in the external secret management systems. ESO will sync the secrets from the external secret management systems to the Kubernetes cluster. Since K8S admin dont have access on the external secret management systems, they cannot update the secrets. ESO will sync the secrets in the background.

5. I have created a Secret for my Database password. How can I use it in the POD?
A: We can pass secrets to the POD in multiple ways:
- Environment Variables
env:
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mysecret
      key: password

- Volume Mounts
volumes:
- name: myvolume
  secret:
    secretName: mysecret

6. What is the best way to assign the secrets to the POD? Is it using Environment Variables or Volume Mounts?
A: It is recommended to use Volume Mounts to assign the secrets to the POD. Because the secrets are mounted as files in the POD. It is not secure than using Environment Variables because if you use Environment Variables, the secrets might be visible in the logs. If you use Volume Mounts, the secrets will be mounted as files in the POD.

Its also recomanded to use the secrets as Volume Mounts because if you use Environment Variables, you need to restart the POD to update the secrets. If you use Volume Mounts, you dont need to restart the POD to update the secrets.

7. How can I update the secrets in the POD without restarting the POD?
A: If you map the secret as Environment Variables, then you need to restart the POD to update the secrets. If you map the secret as Volume Mounts, then you dont need to restart the POD to update the secrets. 

8. How can decrypt the secrets in the Kubernetes cluster?
A: kubectl create secret generic my-secret --from-literal=passphrase=India@123456
kubectl get secrets my-secret  -o json
echo 'SW5kaWFAMTIzNDU2' | base64 -d

9. How can access a secret from the different namespace?
A: Didnt found any information of volume mount with secrets from different namespace. But we can use the kubernetes-reflector extension to access the secrets from the different namespace. 
You cannot access the secret as Environment Variables from the different namespace.
TLS Secret is namespace specific. If you want to access the TLS secret from the different namespace, you need to copy the TLS secret to the different namespace.

Accessing secret in a different namespace will give CreateContainerConfigError.

Using kubernetes-reflector Extension:
$ kubectl apply -f https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml
https://www.baeldung.com/ops/kubernetes-namespaces-common-secrets

10. What are configMaps?
A: ConfigMaps are used to store the configuration data in the Kubernetes cluster. It is used to store the non-sensitive data like application configuration, properties files etc. nginx configuration files, application.properties files etc.mysql.properties files etc.

11. How to use configMaps in the POD?
A: We can use the configMaps in the POD in multiple ways:
- Environment Variables
  - name: DB_URL
    valueFrom:
      configMapKeyRef:
        name: myconfigmap
        key: url
- Volume Mounts
  volumes:
  - name: myvolume
    configMap:
      name: myconfigmap

12. How to update the configMaps in the POD without restarting the POD?
A: If you map the configMap as Environment Variables, then you need to restart the POD to update the configMap. If you map the configMap as Volume Mounts, then you dont need to restart the POD to update the configMap.

13. Can I use Secrets and ConfigMaps in the same POD?
A: Yes, you can use the Secrets and ConfigMaps in the same POD. You can use the Secrets as Environment Variables and ConfigMaps as Volume Mounts.

14. How do you ceate a ConfigMap?
A: kubectl create configmap myconfigmap --from-literal=url=http://mydb.com --from-literal=port=3306
From File:
kubectl create configmap myconfigmap --from-file=config.properties