#Ingress for vote.k8sb30.xyz
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "vote.k8sb30.xyz"
    - "www.k8sb30.xyz"
    secretName: wc-tls-secret
  rules:
  - host: vote.k8sb30.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80
  - host: www.k8sb30.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80

#Ingress for naked k8sb30.xyz domain
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress-naked
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "k8sb30.xyz"
    secretName: nk-tls-secret
  rules:
  - host: k8sb30.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80